### ISSUE TITLE
bug in odometry calculation for husky_gazebo_plugin

### ISSUE THREAD

**Issue by ravirathnam** [husky/husky_simulator#1]
I noticed while driving the husky around in gazebo, that rotating causes a rotation around the y axis for the odometry. Since gazebo, clearpath and rviz, all use a coordinate system with the z axis pointed up, any rotation needs to be around the z axis. This is a one line fix, with changing
qt.setEuler(odom_pos_[2], 0,0);
to
qt.setEulerZYX(odom_pos_[2], 0,0);

**Comment by mikepurvis** [comment]
@y22ma, this bug was fixed in 2c32b8d74529ccc3782578eadf2ee986a6a85b8c, was it not?

**Comment by ravirathnam** [comment]
yes, it is fixed now
