### ISSUE TITLE
Husky arm controllers aren't loading in simulation, two ros_controls

### ISSUE THREAD

**Issue by UltronDestroyer** [husky/husky_simulator#19]
[ERROR] [WallTime: 1427219885.816407] [4.851000] Failed to load arm_controller
Initializing controller 'arm_controller' failed
[ERROR] [1427219885.187761475, 4.317000000]: Could not find joint name on param server

However, the action servers are available, but it's saying controllers aren't up.

Seems to be loading ros_control plugin twice:
h/.ros/log/4c4a6722-d24f-11e4-8ff8-b870f4db1118/spawn_husky_model-12*.log
[ INFO] [1427219884.083360210, 3.665000000]: Loading gazebo_ros_control plugin
[ INFO] [1427219884.083501750, 3.665000000]: Starting gazebo_ros_control plugin in namespace: /
[ INFO] [1427219884.086100954, 3.665000000]: gazebo_ros_control plugin is waiting for model URDF in parameter [robot_description] on the ROS param server.
[ERROR] [1427219884.189958956, 3.665000000]: No type element found in transmission 'r_gripper_trans'.
[ INFO] [1427219884.392373536, 3.665000000]: Loaded gazebo_ros_control.
[ INFO] [1427219884.423898454, 3.665000000]: f3d plugin missing <frameName>, defaults to world

**Comment by UltronDestroyer** [comment]
Fix would be when the arm urdf is included (it is also loading ros_control), to not call ros_control inside description.gazebo.xacro.

**Comment by UltronDestroyer** [comment]
Nevermind, not the issue here.

**Comment by cretaceous-creature** [comment]
I also get this error and the gripper could not move. I did not catch the fix method, do you mean remove the gazebo_ros_control in description.gazebo.xacro file?
