### ISSUE TITLE
Why do we use hector_gazebo_imu and hector_gazebo_gps?

### ISSUE THREAD

**Issue by UltronDestroyer** [husky/husky_simulator#28]
In here we use 

https://github.com/husky/husky_simulator/blob/kinetic-devel/husky_gazebo/urdf/husky.gazebo.xacro#L33

Why that instead of the gazebo ones?

**Comment by mikepurvis** [comment]
Mostly historical— prior to Gazebo 7, there wasn't a standard GPS plugin. And the standard IMU plugin did weird things like not have a gravity vector, so it was easier to use one from the community which was more consistent with our real-world sensors.

**Comment by UltronDestroyer** [comment]
Sounds good. for Indigo I'll leave it Hector, but Kinetic, I'll be moving it to Gz7's plugin
