### ISSUE TITLE
[WARN]: Controller Spawner couldn't find the expected controller_manager ROS Interface

### ISSUE THREAD

**Issue by aranganath** [husky/husky_simulator#29]
Hi,

  I've been trying to run the husky_gazebo node.. But for some reason, I'm not able to control husky using the teleop_keyboard.

The status once I run roslaunch husky_gazebo husky_playpen.launch is:

... logging to /home/aditya/.ros/log/956de5ca-06c6-11e7-ac58-c8ff287985b5/roslaunch-aditya-Lenovo-Yoga710-14ISK-13541.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: Traditional processing is deprecated. Switch to --inorder processing!
To check for compatibility of your document, use option --check-order.
For more infos, see http://wiki.ros.org/xacro#Processing_Order
deprecated: xacro tags should be prepended with 'xacro' xml namespace.
Use the following script to fix incorrect usage:
        find . -iname "*.xacro" | xargs sed -i 's#<\([/]\?\)\(if\|unless\|include\|arg\|property\|macro\|insert_block\)#<\1xacro:\2#g'
when processing file: /home/aditya/CSE180/src/husky_gazebo/urdf/description.gazebo.xacro

xacro.py is deprecated; please use xacro instead
started roslaunch server http://aditya-Lenovo-Yoga710-14ISK:37005/

SUMMARY
========

PARAMETERS
 * /ekf_localization/base_link_frame: base_link
 * /ekf_localization/frequency: 50
 * /ekf_localization/imu0: imu/data
 * /ekf_localization/imu0_config: [False, False, Fa...
 * /ekf_localization/imu0_differential: True
 * /ekf_localization/imu0_queue_size: 10
 * /ekf_localization/imu0_remove_gravitational_acceleration: True
 * /ekf_localization/odom0: husky_velocity_co...
 * /ekf_localization/odom0_config: [False, False, Fa...
 * /ekf_localization/odom0_differential: False
 * /ekf_localization/odom0_queue_size: 10
 * /ekf_localization/odom_frame: odom
 * /ekf_localization/two_d_mode: True
 * /ekf_localization/world_frame: odom
 * /husky_joint_publisher/publish_rate: 50
 * /husky_joint_publisher/type: joint_state_contr...
 * /husky_velocity_controller/angular/z/has_acceleration_limits: True
 * /husky_velocity_controller/angular/z/has_velocity_limits: True
 * /husky_velocity_controller/angular/z/max_acceleration: 6.0
 * /husky_velocity_controller/angular/z/max_velocity: 2.0
 * /husky_velocity_controller/base_frame_id: base_link
 * /husky_velocity_controller/cmd_vel_timeout: 0.25
 * /husky_velocity_controller/enable_odom_tf: False
 * /husky_velocity_controller/estimate_velocity_from_position: False
 * /husky_velocity_controller/left_wheel: ['front_left_whee...
 * /husky_velocity_controller/linear/x/has_acceleration_limits: True
 * /husky_velocity_controller/linear/x/has_velocity_limits: True
 * /husky_velocity_controller/linear/x/max_acceleration: 3.0
 * /husky_velocity_controller/linear/x/max_velocity: 1.0
 * /husky_velocity_controller/pose_covariance_diagonal: [0.001, 0.001, 0....
 * /husky_velocity_controller/publish_rate: 50
 * /husky_velocity_controller/right_wheel: ['front_right_whe...
 * /husky_velocity_controller/twist_covariance_diagonal: [0.001, 0.001, 0....
 * /husky_velocity_controller/type: diff_drive_contro...
 * /husky_velocity_controller/wheel_radius_multiplier: 1.0
 * /husky_velocity_controller/wheel_separation_multiplier: 1.875
 * /robot_description: <?xml version="1....
 * /rosdistro: kinetic
 * /rosversion: 1.12.6
 * /twist_mux/locks: [{'topic': 'e_sto...
 * /twist_mux/topics: [{'topic': 'joy_t...
 * /use_sim_time: True

NODES
  /
    base_controller_spawner (controller_manager/spawner)
    ekf_localization (robot_localization/ekf_localization_node)
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    spawn_husky_model (gazebo_ros/spawn_model)
    twist_marker_server (interactive_marker_twist_server/marker_server)
    twist_mux (twist_mux/twist_mux)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[gazebo-1]: started with pid [13562]
process[gazebo_gui-2]: started with pid [13567]
process[robot_state_publisher-3]: started with pid [13572]
process[base_controller_spawner-4]: started with pid [13573]
process[ekf_localization-5]: started with pid [13580]
process[twist_marker_server-6]: started with pid [13593]
process[twist_mux-7]: started with pid [13599]
process[spawn_husky_model-8]: started with pid [13625]
[ INFO] [1489285026.759704645]: [twist_marker_server] Initialized.
[ INFO] [1489285026.963734797]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1489285026.964849792]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1489285027.836769729, 1298.500000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1489285027.885431704, 1298.550000000]: Physics dynamic reconfigure ready.
Warning [parser_urdf.cc:1232] multiple inconsistent <gravity> exists due to fixed joint reduction overwriting previous value [true] with [false].
[ INFO] [1489285028.861646869, 1298.680000000]: Laser Plugin (robotNamespace = /), Info: Using the 'robotNamespace' param: '/'
[ INFO] [1489285028.861787644, 1298.680000000]: Starting Laser Plugin (ns = /)!
[ INFO] [1489285028.863121697, 1298.680000000]: Laser Plugin (ns = /)  <tf_prefix_>, set to ""
[spawn_husky_model-8] process has finished cleanly
log file: /home/aditya/.ros/log/956de5ca-06c6-11e7-ac58-c8ff287985b5/spawn_husky_model-8*.log
[WARN] [1489285057.209350, 1326.810000]: Controller Spawner couldn't find the expected controller_manager ROS interface.
[base_controller_spawner-4] process has finished cleanly
log file: /home/aditya/.ros/log/956de5ca-06c6-11e7-ac58-c8ff287985b5/base_controller_spawner-4*.log

I have tried the answers here:
http://answers.ros.org/question/214712/gazebo-controller-spawner-warning/

But sadly in vain. I have managed to run it on other machines. But it refuses to run on mine.

ros debugger (roswtf) returns the following:

Loaded plugin tf.tfwtf
No package or stack in context
================================================================================
Static checks summary:

No errors or warnings
================================================================================
Beginning tests of your ROS graph. These may take awhile...
analyzing graph...
... done analyzing graph
running graph rules...
... done running graph rules
running tf checks, this will take a second...
... tf checks complete

Online checks summary:

Found 3 warning(s).
Warnings are things that may be just fine, but are sometimes at fault

WARNING The following node subscriptions are unconnected:
 * /robot_state_publisher:
   * /joint_states
 * /twist_marker_server:
   * /twist_marker_server/feedback
 * /rqt_gui_py_node_13212:
   * /statistics
 * /ekf_localization:
   * /husky_velocity_controller/odom
   * /imu/data
   * /set_pose
 * /twist_mux:
   * /e_stop
   * /cmd_vel
   * /platform_control/cmd_vel
   * /joy_teleop/cmd_vel
 * /gazebo:
   * /gazebo/set_model_state
   * /gazebo/set_link_state

WARNING These nodes have died:
 * spawn_husky_model-8
 * base_controller_spawner-4

WARNING Received out-of-date/future transforms:
 * receiving transform from [/slam_gmapping] that differed from ROS time by 1489300903.76s

running rostopic echo husky_velocity_controller/cmd_vel gives me:
rostopic echo /husky_velocity_controller/cmd_vel 
WARNING: no messages received and simulated time is active.
Is /clock being published?

FOr which I have tried the solution given in the link below:
http://answers.ros.org/question/12083/messages-being-blocked-from-publishing/

I have attached the image below to show how my graph currently looks like
![image](https://cloud.githubusercontent.com/assets/26356929/23829941/19e2a8c2-06b3-11e7-855c-f597a806f02d.png)

I have controller_manager installed. But it doesn't seem to load when I launch gazebo.

Kindly let me know what the issue could be !
Regards

**Comment by David-Guo** [comment]
@aranganath I meet the same error. Did you solve this ?

**Comment by aranganath** [comment]
Try this:sudo apt-get install ros-kinetic-gazebo-ros-control. Worked for me!
