### ISSUE TITLE
Add GPS and IMU Sensor Simulations 

### ISSUE THREAD

**Issue by pmukherj** [husky/husky_simulator#3]
Not incredibly high priority but would be nice to have.

**Comment by rohanbhargava11** [comment]
Is there any update on adding standard sensors to the simulator? 

I have added imu from hector_gazebo_plugins. Similarly I am planning to add gps from that as well. I was wondering where in the robot should they be placed (in terms of coordinates or with respect to base_link)? I am not sure about the location of the sensors as I don't have a husky with me.

**Comment by mikepurvis** [comment]
The pose of the standard IMU is expressed by a static transform publisher in this launch file:

https://github.com/husky/husky_bringup/blob/hydro-devel/launch/imu_config/um6.launch

However, there is a ticket to move that transform into the default URDF: https://github.com/husky/husky_description/issues/3

Would happily merge a PR to that effect, especially if it aids in providing a more accurate simulator.

**Comment by pmukherj** [comment]
On that note. A simulator with GPS and LIDAR is currently being tested on the 'simulator_cleanup' branch of the various packages (husky_simulator, husky_description). Its not a good long term solution because its using an external plugin, a better solution is planned for Gazebo 2.0 as per this conversation (https://github.com/ros-simulation/gazebo_ros_pkgs/issues/154)

**Comment by rohanbhargava11** [comment]
Ah I see. I will start working with simulator_cleanup branch. It looks like you guys have got the imu, gps and laser on the husky. Thanks for the link.

**Comment by pmukherj** [comment]
Sweet! Please let us know if you have any issues with it!

**Comment by pmukherj** [comment]
This issue was resolved on this PR: https://github.com/husky/husky_simulator/commit/9c258f7fc1f380e6695f7acca3d69d01febb833e
