### ISSUE TITLE
have some problem with install from source

### ISSUE THREAD

**Issue by ghost** [husky/husky_simulator#33]
I DO:
git clone https://github.com/husky/husky.git
git clone https://github.com/husky/husky_simulator.git
git clone https://github.com/husky/husky_desktop.git
cd ..
catkin build 
export HUSKY_GAZEBO_DESCRIPTION=$(rospack find husky_gazebo)/urdf/description.gazebo.xacro
roslaunch husky_gazebo husky_playpen.launch
but:
show error:
xacro.XacroException: included file "/home/jj/gzros_ws/src/husky_simulator/husky_gazebo/urdf/empty.urdf" could not be opened: [Errno 2] No such file or directory: '/home/jj/gzros_ws/src/husky_simulator/husky_gazebo/urdf/empty.urdf'
while processing /home/jj/gzros_ws/src/husky_simulator/husky_gazebo/launch/husky_empty_world.launch:
while processing /home/jj/gzros_ws/src/husky_simulator/husky_gazebo/launch/spawn_husky.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/indigo/share/xacro/xacro.py '/home/jj/gzros_ws/src/husky_simulator/husky_gazebo/urdf/description.gazebo.xacro'     laser_enabled:=true     ur5_enabled:=false     kinect_enabled:=false     ] returned with code [1]. 

Param xml is <param command="$(find xacro)/xacro.py '$(arg husky_gazebo_description)'     laser_enabled:=$(arg laser_enabled)     ur5_enabled:=$(arg ur5_enabled)     kinect_enabled:=$(arg kinect_enabled)     " name="robot_description"/>
The traceback for the exception was written to the log file

how can i solve it?

**Comment by wojiaojiao** [comment]
i find the issues:
in spawn_husky.launch
<param name="robot_description" command="$(find xacro)/xacro.py '$(arg husky_gazebo_description)'
    laser_enabled:=$(arg laser_enabled)
    ur5_enabled:=$(arg ur5_enabled)
    kinect_enabled:=$(arg kinect_enabled)
    " />
how do  i modify they?

**Comment by wojiaojiao** [comment]
i find the issues:
in spawn_husky.launch
<param name="robot_description" command="$(find xacro)/xacro.py '$(arg husky_gazebo_description)'
    laser_enabled:=$(arg laser_enabled)
    ur5_enabled:=$(arg ur5_enabled)
    kinect_enabled:=$(arg kinect_enabled)
    " />
how do i modify they?

**Comment by wojiaojiao** [comment]
param name="robot_description" command="$(find xacro)/xacro.py '$(arg husky_gazebo_description)'
    laser_enabled:=$(arg laser_enabled)
    ur5_enabled:=$(arg ur5_enabled)
    kinect_enabled:=$(arg kinect_enabled)

**Comment by wojiaojiao** [comment]
i find the issues:
in spawn_husky.launch
param name="robot_description" command="$(find xacro)/xacro.py '$(arg husky_gazebo_description)'
laser_enabled:=$(arg laser_enabled)
ur5_enabled:=$(arg ur5_enabled)
kinect_enabled:=$(arg kinect_enabled)

how do i modify they?

**Comment by wojiaojiao** [comment]
http://answers.gazebosim.org/question/7777/invalid-param-tag-cannot-load-husky-into-gazebo/
 rahul@rahul-pc:~/husky_ws$ roslaunch husky_gazebo husky_empty_world.launch 
... logging to /home/rahul/.ros/log/014e7106-9478-11e4-b211-a4db30d7dfe6/roslaunch-rahul-pc-4352.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

Traceback (most recent call last):
  File "/opt/ros/indigo/share/xacro/xacro.py", line 60, in <module>
    xacro.main()
AttributeError: 'module' object has no attribute 'main'
while processing /home/rahul/sample_ws/src/husky_gazebo/launch/base.urdf.gazebo.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/indigo/share/xacro/xacro.py        '/home/rahul/sample_ws/src/husky_description/urdf/base.urdf.xacro'          gps_enabled:=true         imu_enabled:=true  front_laser:=true     ] returned with code [1]. 

Param xml is <param command="$(find xacro)/xacro.py        '$(find husky_description)/urdf/base.urdf.xacro'          gps_enabled:=$(arg gps_enabled)         imu_enabled:=$(arg imu_enabled)  front_laser:=$(arg front_laser)     " name="robot_description"/>
The traceback for the exception was written to the log file

**Comment by dniewinski** [comment]
It looks like this is my mistake, sorry that you found it for me.  To work around this for now, use the following command before launching gazebo.  This is just a stop-gap to get you going while I look into a proper fix:

export HUSKY_URDF_EXTRAS=$(rospack find husky_description)/urdf/empty.urdf

**Comment by ghost** [comment]
@dniewinski  thanks very much!
