### ISSUE TITLE
Release for ROS Kinetic

### ISSUE THREAD

**Issue by pfankhauser** [husky/husky_simulator#35]
We run a [ROS course](http://www.rsl.ethz.ch/education-students/lectures/ros.html) where we use the Husky simulator as an exercise. For ease of use, it would be great to have a release version of the `husky_simulator` packages for ROS Kinetic (currently only up to Indigo). Is there any plan for that?

**Comment by tonybaltovski** [comment]
Hi @pfankhauser, the Husky package contains the Kinetic [branch](https://github.com/husky/husky/tree/kinetic-devel).  Releasing the package is will be in the near future.

**Comment by pfankhauser** [comment]
Hi @tonybaltovski 
Thanks for info! I'm aware of the Kinetic branch, but we're really interested in the released packages through the PPA pipeline. Is there an estimate of what you mean by "near future"?
Thanks, Péter

**Comment by tonybaltovski** [comment]
@pfankhauser We recently released the Husky packages for Kinetic. They aren't in the main repository but in [shadow-fixed](http://wiki.ros.org/ShadowRepository). That would be the best way to get the simulation running till they are synced.

**Comment by pfankhauser** [comment]
Great, thanks for letting us know! @djud, @martiwer

**Comment by dniewinski** [comment]
Despite many delays, we have finally finished and released support for Kinetic! Many of the packages should be available through http://packages.ros.org or from http://packages.clearpathrobotics.com
