### ISSUE TITLE
Cant run the simulation in indigo

### ISSUE THREAD

**Issue by tiberium24** [husky/husky_simulator#36]
Hello, 

I posted a question yesterday also but still i can't get the simulation to run on indigo. I downloaded the indigo branch this time, but when i try to launch the empty world file i get the following:

Do you know what could be causing this ? Thank you very much

Traceback (most recent call last):
  File "/opt/ros/indigo/share/xacro/xacro.py", line 62, in <module>
    xacro.main()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 673, in main
    f = open(args[0])
IOError: [Errno 2] No such file or directory: ''
while processing /home/john/husky_indigo_ws/src/husky_gazebo/launch/spawn_husky.launch:
Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/indigo/share/xacro/xacro.py ''     laser_enabled:=true     ur5_enabled:=false     kinect_enabled:=false     ] returned with code [1].

**Comment by tonybaltovski** [comment]
Did you install all the deps?

**Comment by caguero** [comment]
It seems that this repository has been deprecated. Use https://github.com/husky/husky instead.

**Comment by tonybaltovski** [comment]
@caguero This is the correct repo for Indigo.

**Comment by tiberium24** [comment]
It had to do something with the laser, i later installed on kinetic and fixed some dependency issues which finally got it working.Thank you
