### ISSUE TITLE
Deprecated repository

### ISSUE THREAD

**Issue by caguero** [husky/husky_simulator#37]
As far as I know, this repository has been deprecated. Should we mark it as officially deprecated, and redirect users to https://github.com/husky/husky?

I see other repos deprecated when browsing over https://github.com/husky. It might confuse users if we don't explicitly do it.

**Comment by tonybaltovski** [comment]
@caguero this has indeed been deprecated for kinetic but not indigo and prior.  I added a note to the repo description.

**Comment by caguero** [comment]
Thanks.
