### ISSUE TITLE
GPS and IMU in Gazebo simulator

### ISSUE THREAD

**Issue by tiberium24** [husky/husky_simulator#38]
Hello,

I am trying to run Gazebo simulation and also want to have a gps and imu on husky publishing on a topic. Is that available?

Thank you

**Comment by dniewinski** [comment]
If you run "roslaunch husky_gazebo husky_playpen.launch" it should open a gazebo simulation with a Husky.  By default, it should publish IMU data on the /imu/data topic and GPS data on /navsat/fix.  Is it not doing this?

**Comment by tiberium24** [comment]
Its working . Thank you
