### ISSUE TITLE
Improper husky figure formed in gazebo 

### ISSUE THREAD

**Issue by abhileshborode** [husky/husky_simulator#39]
I am using ROS kinetic. I have a package which launches the husky robot in gazebo, however the gazebo figure launched looks like this:
[
![screenshot from 2018-10-07 19-01-30](https://user-images.githubusercontent.com/33388291/47060914-94fc7600-d18c-11e8-9afc-e46dcb25bc31.png)
]
Please let me know if editing any particular urdf files would fix this issue or not ?

**Comment by tonybaltovski** [comment]
Did you get any errors when you launch this?

**Comment by abhileshborode** [comment]
NO errors ....I am able to publish the velocity commands and the ("so seen husky") model moves , but due to an improper model the the husky goes past the wall in gazebo when it is not suppose to do so. 

EDIT: I just noticed this error:
[ERROR] [1539901090.917272815]: SpawnModel: Failure - model name mobile_base already exist.

Is it possible this is the issue.?

If so how can I get rid of it ?
