### ISSUE TITLE
Not getting imu-data in husky gazebo simulation

### ISSUE THREAD

**Issue by Debojyoti7** [husky/husky_simulator#43]
I'm not getting any data on /imu/data. I also installed imu_tools package but still no data. Any help?

**Comment by tonybaltovski** [comment]
Please use: https://github.com/husky/husky

**Comment by Debojyoti7** [comment]
> Please use: https://github.com/husky/husky
Yes using that. But not getting any output in /imu/data.
Both for ros melodic and also in kinetic systems.

**Comment by Debojyoti7** [comment]
Thanks for help.  Anyway I was able to solve it by installing gazebo_ros_imu plugin
